---
- name: Deploy Spam Detection App
  hosts: prod
  become: false

  tasks:
    - name: Stop and remove container if exists
      community.docker.docker_container:
        name: "{{ docker_image_name }}"
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: "{{ docker_image_name }}"
        image: "{{ docker_image_user }}/{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "9000:5000"
